#!/usr/bin/env bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=64
#SBATCH --time=12:00:00
#SBATCH --mem=50GB
#SBATCH --output=slurm.log
#SBATCH --job-name=nanopore-peptide-detection

JOBS=150

# Ensure log dir for SLURM jobs generated by snakemake exists
mkdir -p results/logs/slurm

conda run --prefix ./env --live-stream \
  snakemake --profile ./workflow/slurm --use-conda --jobs "$JOBS" --retries 2 --local-cores 4  --rerun-incomplete
